CREATE DATABASE IF NOT EXISTS driver_management;
CREATE DATABASE IF NOT EXISTS vehicle_management;
CREATE DATABASE IF NOT EXISTS assignments;
CREATE DATABASE IF NOT EXISTS maintenance_repairs;
CREATE DATABASE IF NOT EXISTS scheduling;
CREATE DATABASE IF NOT EXISTS fuel_consumption;
CREATE DATABASE IF NOT EXISTS tasks_services;
